# Day 6: NumPy

**NumPy** (Numerical Python) is the fundamental package for scientific computing in Python.

---

## Topics Covered:
1. Arrays, Shapes, and Dtypes
2. Indexing, Slicing, and Broadcasting
3. Mathematical Operations
4. Linear Algebra Basics


In [2]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.2.6


## 1. Creating Arrays

NumPy arrays are the core data structure — fast, memory-efficient, and support vectorized operations.

### Key Ways to Create Arrays:
| Function | Description |
|----------|-------------|
| `np.array()` | From a Python list |
| `np.zeros()` | Array of zeros |
| `np.ones()` | Array of ones |
| `np.arange()` | Range with step |
| `np.linspace()` | Evenly spaced values |
| `np.eye()` | Identity matrix |
| `np.random.rand()` | Random values [0, 1) |

In [3]:
# Creating arrays from lists
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)

# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\n2D array:")
print(b)

1D array: [1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]]


In [4]:
# Built-in array creation functions
print("Zeros (3x4):")
print(np.zeros((3, 4)))

print("\nOnes (2x3):")
print(np.ones((2, 3)))

print("\nArange (0 to 10, step 2):", np.arange(0, 10, 2))

print("\nLinspace (0 to 1, 5 values):", np.linspace(0, 1, 5))

print("\nIdentity matrix (3x3):")
print(np.eye(3))

print("\nFull array (2x2, filled with 7):")
print(np.full((2, 2), 7))

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Arange (0 to 10, step 2): [0 2 4 6 8]

Linspace (0 to 1, 5 values): [0.   0.25 0.5  0.75 1.  ]

Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Full array (2x2, filled with 7):
[[7 7]
 [7 7]]


In [5]:
# Random arrays
print("Random (3x3):")
print(np.random.rand(3, 3))

print("\nRandom integers (1-10, shape 2x3):")
print(np.random.randint(1, 10, size=(2, 3)))

Random (3x3):
[[0.07165076 0.20780257 0.06126448]
 [0.65583816 0.15578488 0.41606367]
 [0.32073059 0.6151847  0.30650906]]

Random integers (1-10, shape 2x3):
[[2 1 5]
 [4 6 6]]


## 2. Shape, Size, and Dimensions

Every array has:
- **shape** — tuple of dimension sizes (rows, columns, ...)
- **ndim** — number of dimensions
- **size** — total number of elements
- **dtype** — data type of elements

In [6]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"Array:\n{arr}")
print(f"\nShape: {arr.shape}")       # (3, 4)
print(f"Dimensions: {arr.ndim}")     # 2
print(f"Size: {arr.size}")           # 12
print(f"Dtype: {arr.dtype}")         # int64
print(f"Item size: {arr.itemsize} bytes")  # 8

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Dtype: int64
Item size: 8 bytes


In [7]:
# Reshaping arrays
print("Original shape:", arr.shape)

reshaped = arr.reshape(4, 3)
print(f"\nReshaped to (4,3):\n{reshaped}")

flattened = arr.flatten()
print(f"\nFlattened: {flattened}")

transposed = arr.T
print(f"\nTransposed (4x3):\n{transposed}")

Original shape: (3, 4)

Reshaped to (4,3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Transposed (4x3):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 3. Data Types (dtypes)

NumPy arrays have a **fixed data type** — all elements are the same type.

| dtype | Description |
|-------|-------------|
| `int32`, `int64` | Integers |
| `float32`, `float64` | Floating point |
| `bool` | Boolean |
| `complex64` | Complex numbers |
| `str_` | Strings |

In [8]:
# Specifying dtype
a = np.array([1, 2, 3], dtype=np.float64)
print(f"Float array: {a}, dtype: {a.dtype}")

# Type casting
b = a.astype(np.int32)
print(f"Int array: {b}, dtype: {b.dtype}")

# Boolean array
c = np.array([True, False, True, False])
print(f"Bool array: {c}, dtype: {c.dtype}")

Float array: [1. 2. 3.], dtype: float64
Int array: [1 2 3], dtype: int32
Bool array: [ True False  True False], dtype: bool


## 4. Indexing

Access individual elements or groups of elements using:
- **Basic indexing** — single element by position
- **Boolean indexing** — filter by condition
- **Fancy indexing** — select by list of indices

In [9]:
# 1D indexing
a = np.array([10, 20, 30, 40, 50])
print(f"a[0] = {a[0]}")     # 10
print(f"a[-1] = {a[-1]}")   # 50

# 2D indexing
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(f"\nb[0, 0] = {b[0, 0]}")   # 1
print(f"b[1, 2] = {b[1, 2]}")     # 6
print(f"b[2, -1] = {b[2, -1]}")   # 9

a[0] = 10
a[-1] = 50

b[0, 0] = 1
b[1, 2] = 6
b[2, -1] = 9


In [10]:
# Boolean indexing (filtering)
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
mask = a > 4
print(f"Mask (a > 4): {mask}")
print(f"Filtered: {a[mask]}")

# Fancy indexing
indices = [0, 2, 5]
print(f"\nFancy indexing [0, 2, 5]: {a[indices]}")

Mask (a > 4): [False False False False  True  True  True  True]
Filtered: [5 6 7 8]

Fancy indexing [0, 2, 5]: [1 3 6]


## 5. Slicing

Syntax: `array[start:stop:step]`

- Works like Python list slicing but extends to multiple dimensions
- **Important:** Slices are *views* (not copies) — modifying a slice modifies the original!

In [11]:
# 1D slicing
a = np.arange(10)
print(f"a = {a}")
print(f"a[2:7] = {a[2:7]}")
print(f"a[::2] = {a[::2]}")
print(f"a[::-1] = {a[::-1]}")

# 2D slicing
b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(f"\nFirst 2 rows:\n{b[:2]}")
print(f"\nColumn 1: {b[:, 1]}")
print(f"\nSub-matrix (rows 0-1, cols 1-2):\n{b[0:2, 1:3]}")

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7] = [2 3 4 5 6]
a[::2] = [0 2 4 6 8]
a[::-1] = [9 8 7 6 5 4 3 2 1 0]

First 2 rows:
[[1 2 3 4]
 [5 6 7 8]]

Column 1: [ 2  6 10]

Sub-matrix (rows 0-1, cols 1-2):
[[2 3]
 [6 7]]


## 6. Broadcasting

Broadcasting allows NumPy to perform operations on arrays with **different shapes**.

### Broadcasting Rules:
1. Dimensions are compared from the **trailing** (rightmost) side
2. Dimensions must be **equal**, OR one of them must be **1**
3. The smaller array is "stretched" to match the larger one

In [12]:
# Scalar broadcasting
a = np.array([1, 2, 3])
print(f"a * 2 = {a * 2}")
print(f"a + 10 = {a + 10}")

# 2D + 1D broadcasting
b = np.array([[1, 2, 3],
              [4, 5, 6]])
c = np.array([10, 20, 30])
print(f"\nb + c =\n{b + c}")

# Column broadcasting
d = np.array([[1],
              [2]])
print(f"\nb + d =\n{b + d}")

a * 2 = [2 4 6]
a + 10 = [11 12 13]

b + c =
[[11 22 33]
 [14 25 36]]

b + d =
[[2 3 4]
 [6 7 8]]


## 7. Mathematical Operations

NumPy operations are **vectorized** — they apply element-by-element without explicit loops.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Arithmetic operations
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

# Mathematical functions
print(f"\nsqrt(a) = {np.sqrt(a)}")
print(f"exp(a) = {np.exp(a)}")
print(f"log(a) = {np.log(a)}")

In [ ]:
# Aggregation functions
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(f"Sum (all): {np.sum(arr)}")
print(f"Sum (columns, axis=0): {np.sum(arr, axis=0)}")
print(f"Sum (rows, axis=1): {np.sum(arr, axis=1)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std: {np.std(arr):.4f}")
print(f"Min: {np.min(arr)}, Max: {np.max(arr)}")
print(f"Argmax (flattened): {np.argmax(arr)}")

In [ ]:
# Comparison and conditional
a = np.array([1, 2, 3, 4, 5])
print(f"a > 3: {a > 3}")
print(f"np.where(a > 3, a, 0): {np.where(a > 3, a, 0)}")

## 8. Linear Algebra Basics

NumPy's `linalg` module provides essential linear algebra operations:
- Matrix multiplication (`@` or `np.dot`)
- Determinant, Inverse, Eigenvalues
- Solving linear systems

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication
C = A @ B
print(f"A @ B =\n{C}")

# Transpose
print(f"\nA transposed:\n{A.T}")

# Determinant
det = np.linalg.det(A)
print(f"\nDeterminant of A: {det:.2f}")

# Inverse
inv = np.linalg.inv(A)
print(f"\nInverse of A:\n{inv}")

# Verify: A @ A_inv = Identity
print(f"\nA @ inv(A):\n{np.round(A @ inv, 2)}")

In [ ]:
# Eigenvalues and Eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Eigenvalues: {eigvals}")
print(f"Eigenvectors:\n{eigvecs}")

In [ ]:
# Solving linear systems: Ax = b
# 2x + 3y = 8
# 4x + y  = 5

A = np.array([[2, 3],
              [4, 1]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print(f"Solution: x = {x[0]:.4f}, y = {x[1]:.4f}")

# Verify
print(f"Verification: A @ x = {A @ x}")
print(f"Expected b = {b}")

## 9. Practice: Matrix Operations Exercises

Try these exercises to solidify your NumPy skills!

In [ ]:
# Exercise 1: Create a 3x3 matrix with values 1-9
# Find its transpose, determinant, and inverse

M = np.arange(1, 10).reshape(3, 3)
print(f"Matrix M:\n{M}")
print(f"\nTranspose:\n{M.T}")
print(f"\nDeterminant: {np.linalg.det(M):.6f}")
# Note: This matrix is singular (det ≈ 0), so inverse doesn't exist
# Let's use a different matrix
M2 = np.array([[2, 1, 3],
               [1, 3, 2],
               [3, 2, 1]])
print(f"\nMatrix M2:\n{M2}")
print(f"Determinant of M2: {np.linalg.det(M2):.4f}")
print(f"Inverse of M2:\n{np.linalg.inv(M2)}")

In [ ]:
# Exercise 2: Random 4x4 matrix — row sums, column means, overall std

np.random.seed(42)
R = np.random.randint(1, 20, size=(4, 4))
print(f"Random matrix:\n{R}")
print(f"\nRow sums: {np.sum(R, axis=1)}")
print(f"Column means: {np.mean(R, axis=0)}")
print(f"Overall std: {np.std(R):.4f}")

In [ ]:
# Exercise 3: Solve the system 3x + 2y = 12, x - y = 1

A = np.array([[3, 2],
              [1, -1]])
b = np.array([12, 1])

solution = np.linalg.solve(A, b)
print(f"Solution: x = {solution[0]:.4f}, y = {solution[1]:.4f}")
print(f"Verification: {A @ solution}")

In [ ]:
# Exercise 5: Normalize a matrix (subtract mean, divide by std per column)

data = np.array([[10, 200, 3000],
                 [20, 400, 6000],
                 [30, 600, 9000],
                 [40, 800, 12000]])

# Column-wise normalization using broadcasting
col_mean = data.mean(axis=0)
col_std = data.std(axis=0)

normalized = (data - col_mean) / col_std

print(f"Original data:\n{data}")
print(f"\nColumn means: {col_mean}")
print(f"Column stds: {col_std}")
print(f"\nNormalized data:\n{normalized}")
print(f"\nVerify — new means: {normalized.mean(axis=0)}")
print(f"Verify — new stds: {normalized.std(axis=0)}")